repos:
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: debug-statements
  - id: flake8
    additional_dependencies: ["flake8-bugbear == 18.8.0"]
    language_version: python3
    exclude: /__init__\.py$
- repo: https://github.com/asottile/pyupgrade
  rev: v1.6.1
  hooks:
  - id: pyupgrade
    language_version: python3
- repo: https://github.com/asottile/seed-isort-config
  rev: v1.3.0
  hooks:
  - id: seed-isort-config
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    language_version: python3
    exclude: /base\.py$
